version: '3'
services:
  api-test-framework:
    image: bxwill/api-test-framework:stable
    container_name: api-test-framework
    restart: always
    volumes:
      - ./atf_workspace:/workspace
    environment:
      TEST_SERVER_URL: <http://api-test-framework>
      TEST_ACCOUNT: <tester>
      TEST_PASSWORD: <password>
